language: php

php:
  - 5.3
  - 5.4

env:
  - MONGO_VERSION=1.3.6
  - MONGO_VERSION=1.2.10

services: mongodb

before_script:
  - printf "\n" | pecl install -f mongo-${MONGO_VERSION}
  - phpenv rehash
  - composer --dev install

script: phpunit
